map('n','<leader>e',':<c-u>Files<CR>', {silent = true })
map('n','<leader>eh',':<c-u>Files ~<CR>', {silent = true })
map('n','<leader>b',':<c-u>Buffers<CR>', {silent = true })
map('n','<leader>g',':<c-u>GFiles<CR>', {silent = true })
map('n','<leader>h',':<c-u>History<CR>', {silent = true })
map('n','<leader>s',':<c-u>Rg<CR>',{silent = true })
map('n','<leader>sh',':<c-u>Rg<CR>',{silent = true })
